version: '3'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    expose:
      - "9000"
    volumes:
      - "../:/home/app/code"
    environment:
      - XDEBUG_CONFIG=remote_host=${XDEBUG_CONFIG_REMOTE_HOST:-host.docker.internal}
      - PHP_IDE_CONFIG=serverName=${PHP_IDE_CONFIG_SERVER_NAME}
